[package]
name = "webapps"
version = "0.4.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "cosmic-webapps"

[profile.dev]
opt-level = 1
overflow-checks = false

[dependencies]
anyhow = "1.0.77"
tracing = "0.1"
tracing-subscriber = "0.3.0"
tokio = { version = "1.37.0", features = ["full"] }
reqwest = { version = "0.11.23", features = ["blocking"] }
rand = "0.8.5"
url = "2.5.0"
walkdir = "2.4.0"
dirs = "5.0"
scraper = "0.18.1"
image = "0.25.1"
usvg = "0.41.0"
lazy_static = "1.4.0"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["dbus-config", "tokio", "winit"]

[features]
default = ["wgpu"]
wgpu = ["libcosmic/wgpu"]

[dependencies.cosmic-files]
git = "https://github.com/pop-os/cosmic-files.git"
default-features = false